### ISSUE TITLE
Initial design/implementation

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#1]
- on drogon have deployment of https://github.com/datalad/dandisets
- on each cron run
  - update full hierarchy: run `datalad update -d dandisets --follow parentds --how=ff-only -J5 -r -R 1` (with `-R 1` we should not get to upgrade zarrs subdatasets for now)
  - install/upgrade virtualenv to most recent version of pynwb/hdmf and matnwb (TODO 4 Yarik: provide matlab on drogon@dandi)
  - use [datalad-fuse](https://github.com/datalad/datalad-fuse/) over https://github.com/datalad/dandisets superdataset
  - in parallel or async fashion operate across dandisets and their assets to check if all .nwb files could be opened, so for each dandiset record status.yaml with following structure

```yaml
last_run: DATETIME
dandiset_version: STR_HEXSHA
nassets: INT  # total number of assets
versions: DICT(name: version) # of relevant versions, e.g. {'pynwb': 1.0.0, 'hdmf': 2.0.0}
tests:
    - name: STR
      assets_ok: LIST(STR)  # which assets were ok
      assets_nok: LIST(STR)  # which assets have failed
```

- target two tests to start with
  - `pynwb_open`: operate on .nwb file and open using pynwb 
  - `matnwb_nwbRead`: operate on .nwb file and open using  matnwb 
- all those .yaml files per each dandiset should be stored in this repo and be similarish to https://github.com/dandi/dandi-api-webshots
  - subfolder per dandiset (we might want to get more information per each dandiset)
  - in each dandiset folder have subfolder `logs` with `{last_run}_{test.name}_errors.log` with output from errored out runs.  That subfolder should be git ignored for now
  - README.md should have summary table with one row per dandiset with one column per test with number of ok/nok assets per that test
