### ISSUE TITLE
Add explicit "status" and "test" to asset records

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets-healthstatus#86]
ATM `status.yaml` groups list into `tests` and then `assets_ok`, `assets_nok`, `assets_timeout` .  In long list, while reviewing it is easy to get lost on which test and the status a given record really is.

I think it would be useful to add to each record `status` (`ok`, `nok`, `timeout`, and may be `untested`) and also `test` (e.g. `matnwb_nwbRead`) so given a record it becomes immediately clear what it is about.

Original groupping would still be preserved since would make it easier to point to the group of failures etc (although could be done also via sorting and pointing to the first record, and thus avoiding explicit groupping).

**Comment by jwodder** [comment]
@yarikoptic So, to be clear, you want the `status.yaml` files to look like:

```yaml
dandiset: '123456'
# Other top level fields omitted
tests:
- assets_nok:
  - path: foo/bar/baz.nwb
    status: nok
    test: matnwb_nwbRead
  - path: gnusto/cleesh.nwb
    status: nok
    test: matnwb_nwbRead
  assets_ok:
    ...
  name: matnwb_nwbRead
```

i.e., repeating the test name & status for each asset in each test?
